@startuml
salt
{
  {+
    [ Historial de Reciclaje ]
    {#
      | Fecha     | Material | Cantidad | Puntos |
      | 01/10/2025 | Plástico | 2        | 10     |
      | 02/10/2025 | Vidrio   | 1        | 8      |
    }
    [ Exportar CSV ] [ Exportar PDF ]
  }
}
@enduml